project:
  type: website

format:
  html:
    theme: superhero
    
website:
  title: "Los extremos del clima"
  navbar:
    right:
      - about.qmd
      - icon: ResearchGate
        href: https://www.researchgate.net/profile/Andres-De-La-Rosa-Portilla-2?ev=hdr_xprf
        
editor: visual

