project:
  type: website

website:
  title: "Herramientas SIG"
  navbar:
    right:
      - about.qmd
      - icon: ResearchGate
        href: https://www.researchgate.net/profile/Andres-De-La-Rosa-Portilla-2?ev=hdr_xprf
        
editor: visual

